import type { LanguageCode } from "@/lib/arogyaApi";

export type Copy = {
  nav: Record<string, string>;
  heroEyebrow: string; heroTitle: string; heroBody: string; talk: string; findCare: string; emergency: string; emergencyBody: string;
  disclaimer: string; serviceOffline: string; retry: string; speak: string; stop: string; listening: string; history: string; newChat: string;
  medicine: string; schemes: string; asha: string; ivr: string; profile: string; save: string; addMedicine: string; dosage: string; time: string; taken: string; snooze: string;
  eligibility: string; checkEligibility: string; nearby: string; allowLocation: string; directions: string; call: string; noResults: string; startIvr: string;
};

const english: Copy = {
  nav: { Home: "Home", Assistant: "AI Assistant", Hospitals: "Hospitals", Medicines: "Medicines", Schemes: "Government Schemes", ASHA: "ASHA Support", IVR: "IVR Simulator", Profile: "Profile" },
  heroEyebrow: "Public healthcare guidance, made clearer", heroTitle: "Bridging Rural Communities to Smart Healthcare.", heroBody: "Ask a question, find care nearby, organise medicine reminders, and explore official programme guidance — in a language you choose.", talk: "Talk to assistant", findCare: "Find hospitals", emergency: "Emergency? Get urgent help", emergencyBody: "For severe chest pain, trouble breathing, heavy bleeding, seizures, unconsciousness, or immediate danger, seek emergency care now. In India, call 112 or 108 where available.", disclaimer: "General health information only. This service does not diagnose, prescribe, or replace a qualified clinician.", serviceOffline: "The Java healthcare service is not reachable. Start the Spring Boot service locally and try again.", retry: "Try again", speak: "Read aloud", stop: "Stop", listening: "Listening…", history: "Saved conversations", newChat: "New conversation", medicine: "Medicine reminders", schemes: "Government health schemes", asha: "ASHA & community support", ivr: "Interactive call simulator", profile: "Your optional profile", save: "Save", addMedicine: "Add medicine", dosage: "Dosage", time: "Reminder time", taken: "Taken", snooze: "Snooze", eligibility: "Eligibility guidance", checkEligibility: "Check my guidance", nearby: "Nearby healthcare", allowLocation: "Use my location", directions: "Directions", call: "Call", noResults: "No results yet.", startIvr: "Start call",
};

function localize(copy: Partial<Copy> & { nav: Record<string, string> }): Copy {
  return { ...english, ...copy, nav: { ...english.nav, ...copy.nav } };
}

export const dictionaries: Record<LanguageCode, Copy> = {
  en: english,
  hi: localize({ nav: { Home: "होम", Assistant: "एआई सहायक", Hospitals: "अस्पताल", Medicines: "दवाइयाँ", Schemes: "सरकारी योजनाएँ", ASHA: "आशा सहायता", IVR: "आईवीआर सिम्युलेटर", Profile: "प्रोफ़ाइल" }, heroEyebrow: "सार्वजनिक स्वास्थ्य मार्गदर्शन, आसान भाषा में", heroTitle: "ग्रामीण समुदायों को स्मार्ट स्वास्थ्य सेवा से जोड़ना।", heroBody: "सवाल पूछें, पास में देखभाल खोजें, दवा की याद दिलाने वाली सूची बनाएं और आधिकारिक योजनाओं की जानकारी देखें।", talk: "सहायक से बात करें", findCare: "अस्पताल खोजें", emergency: "आपातकाल? तुरंत मदद लें", emergencyBody: "सीने में तेज दर्द, सांस लेने में दिक्कत, बहुत अधिक रक्तस्राव, दौरा, बेहोशी या तत्काल खतरे में अभी आपातकालीन सेवा लें। भारत में उपलब्ध होने पर 112 या 108 पर कॉल करें।", disclaimer: "केवल सामान्य स्वास्थ्य जानकारी। यह सेवा निदान या उपचार नहीं करती और चिकित्सक का विकल्प नहीं है।", speak: "सुनें", stop: "रोकें", listening: "सुन रहा है…", medicine: "दवा अनुस्मारक", schemes: "सरकारी स्वास्थ्य योजनाएँ", asha: "आशा और समुदाय सहायता", ivr: "इंटरैक्टिव कॉल सिम्युलेटर", profile: "आपकी वैकल्पिक प्रोफ़ाइल", save: "सहेजें", addMedicine: "दवा जोड़ें", dosage: "खुराक", time: "याद दिलाने का समय", taken: "ली गई", snooze: "थोड़ी देर बाद", eligibility: "पात्रता मार्गदर्शन", checkEligibility: "मार्गदर्शन देखें", nearby: "पास की स्वास्थ्य सेवा", allowLocation: "मेरा स्थान उपयोग करें", directions: "रास्ता", call: "कॉल", noResults: "अभी कोई परिणाम नहीं।", startIvr: "कॉल शुरू करें" }),
  kn: localize({ nav: { Home: "ಮುಖಪುಟ", Assistant: "ಎಐ ಸಹಾಯಕ", Hospitals: "ಆಸ್ಪತ್ರೆಗಳು", Medicines: "ಔಷಧಿಗಳು", Schemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು", ASHA: "ಆಶಾ ಬೆಂಬಲ", IVR: "ಐವಿಆರ್ ಸಿಮ್ಯುಲೇಟರ್", Profile: "ಪ್ರೊಫೈಲ್" }, heroEyebrow: "ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶನ, ಇನ್ನಷ್ಟು ಸರಳವಾಗಿ", heroTitle: "ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳನ್ನು ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಸೇವೆಗೆ ಸಂಪರ್ಕಿಸುವುದು.", heroBody: "ಪ್ರಶ್ನೆ ಕೇಳಿ, ಹತ್ತಿರದ ಆರೈಕೆ ಹುಡುಕಿ, ಔಷಧಿ ಜ್ಞಾಪನೆಗಳನ್ನು ವ್ಯವಸ್ಥೆಗೊಳಿಸಿ ಮತ್ತು ಅಧಿಕೃತ ಯೋಜನೆ ಮಾರ್ಗದರ್ಶನ ನೋಡಿ.", talk: "ಸಹಾಯಕರೊಂದಿಗೆ ಮಾತನಾಡಿ", findCare: "ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ", emergency: "ತುರ್ತು ಪರಿಸ್ಥಿತಿಯೇ? ತಕ್ಷಣ ಸಹಾಯ ಪಡೆಯಿರಿ", emergencyBody: "ತೀವ್ರ ಎದೆನೋವು, ಉಸಿರಾಟದ ತೊಂದರೆ, ಅಧಿಕ ರಕ್ತಸ್ರಾವ, ಸೆಳೆತ, ಪ್ರಜ್ಞೆ ತಪ್ಪುವುದು ಅಥವಾ ತಕ್ಷಣದ ಅಪಾಯ ಇದ್ದರೆ ಈಗಲೇ ತುರ್ತು ಆರೈಕೆ ಪಡೆಯಿರಿ. ಭಾರತದಲ್ಲಿ ಲಭ್ಯವಿದ್ದರೆ 112 ಅಥವಾ 108 ಗೆ ಕರೆ ಮಾಡಿ.", disclaimer: "ಸಾಮಾನ್ಯ ಆರೋಗ್ಯ ಮಾಹಿತಿಗಾಗಿ ಮಾತ್ರ. ಇದು ರೋಗನಿರ್ಣಯ ಅಥವಾ ಚಿಕಿತ್ಸೆ ನೀಡುವುದಿಲ್ಲ ಮತ್ತು ವೈದ್ಯರ ಪರ್ಯಾಯವಲ್ಲ.", speak: "ಗಟ್ಟಿಯಾಗಿ ಓದಿ", stop: "ನಿಲ್ಲಿಸಿ", listening: "ಆಲಿಸುತ್ತಿದೆ…", medicine: "ಔಷಧಿ ಜ್ಞಾಪನೆಗಳು", schemes: "ಸರ್ಕಾರಿ ಆರೋಗ್ಯ ಯೋಜನೆಗಳು", asha: "ಆಶಾ ಮತ್ತು ಸಮುದಾಯ ಬೆಂಬಲ", ivr: "ಸಂವಾದಾತ್ಮಕ ಕರೆ ಸಿಮ್ಯುಲೇಟರ್", profile: "ನಿಮ್ಮ ಐಚ್ಛಿಕ ಪ್ರೊಫೈಲ್", save: "ಉಳಿಸಿ", addMedicine: "ಔಷಧಿ ಸೇರಿಸಿ", dosage: "ಡೋಸ್", time: "ಜ್ಞಾಪನೆ ಸಮಯ", taken: "ತೆಗೆದುಕೊಂಡೆ", snooze: "ಮುಂದೂಡಿ", eligibility: "ಅರ್ಹತೆ ಮಾರ್ಗದರ್ಶನ", checkEligibility: "ನನ್ನ ಮಾರ್ಗದರ್ಶನ ನೋಡಿ", nearby: "ಹತ್ತಿರದ ಆರೋಗ್ಯ ಸೇವೆ", allowLocation: "ನನ್ನ ಸ್ಥಳ ಬಳಸಿ", directions: "ದಾರಿ", call: "ಕರೆ", noResults: "ಇನ್ನೂ ಫಲಿತಾಂಶಗಳಿಲ್ಲ.", startIvr: "ಕರೆ ಆರಂಭಿಸಿ" }),
  ml: localize({ nav: { Home: "ഹോം", Assistant: "എ.ഐ. സഹായി", Hospitals: "ആശുപത്രികൾ", Medicines: "മരുന്നുകൾ", Schemes: "സർക്കാർ പദ്ധതികൾ", ASHA: "ആശാ പിന്തുണ", IVR: "ഐവിആർ സിമുലേറ്റർ", Profile: "പ്രൊഫൈൽ" }, heroEyebrow: "പൊതുജനാരോഗ്യ മാർഗനിർദേശം, കൂടുതൽ വ്യക്തമായി", heroTitle: "ഗ്രാമീണ സമൂഹങ്ങളെ സ്മാർട്ട് ആരോഗ്യസേവനവുമായി ബന്ധിപ്പിക്കുന്നു.", heroBody: "ചോദ്യം ചോദിക്കുക, സമീപത്തെ പരിചരണം കണ്ടെത്തുക, മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ ക്രമീകരിക്കുക, ഔദ്യോഗിക പദ്ധതി മാർഗനിർദേശം പരിശോധിക്കുക.", talk: "സഹായിയോട് സംസാരിക്കുക", findCare: "ആശുപത്രികൾ കണ്ടെത്തുക", emergency: "അടിയന്തരാവസ്ഥയോ? ഉടൻ സഹായം തേടുക", emergencyBody: "നെഞ്ചുവേദന, ശ്വാസതടസ്സം, കനത്ത രക്തസ്രാവം, അപസ്മാരം, ബോധക്ഷയം, അല്ലെങ്കിൽ അടിയന്തര അപകടം ഉണ്ടെങ്കിൽ ഉടൻ പരിചരണം തേടുക. ഇന്ത്യയിൽ 112 അല്ലെങ്കിൽ 108-ൽ വിളിക്കുക.", disclaimer: "പൊതുവായ ആരോഗ്യവിവരങ്ങൾ മാത്രം. ഇത് രോഗനിർണയമോ ചികിത്സയോ നൽകുന്നില്ല.", speak: "ശബ്ദത്തിൽ കേൾക്കുക", stop: "നിർത്തുക", listening: "കേൾക്കുന്നു…", medicine: "മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ", schemes: "സർക്കാർ ആരോഗ്യപദ്ധതികൾ", asha: "ആശാ, സമൂഹ പിന്തുണ", ivr: "ഇന്ററാക്ടീവ് കോൾ സിമുലേറ്റർ", profile: "നിങ്ങളുടെ ഐച്ഛിക പ്രൊഫൈൽ", save: "സേവ് ചെയ്യുക", addMedicine: "മരുന്ന് ചേർക്കുക", dosage: "അളവ്", time: "ഓർമ്മപ്പെടുത്തൽ സമയം", taken: "എടുത്തു", snooze: "പിന്നീട്", eligibility: "അർഹതാ മാർഗനിർദേശം", checkEligibility: "എന്റെ മാർഗനിർദേശം കാണുക", nearby: "സമീപത്തെ ആരോഗ്യസേവനം", allowLocation: "എന്റെ സ്ഥാനം ഉപയോഗിക്കുക", directions: "വഴിനിർദേശം", call: "വിളിക്കുക", noResults: "ഇതുവരെ ഫലങ്ങളില്ല.", startIvr: "കോൾ ആരംഭിക്കുക" }),
  ta: localize({ nav: { Home: "முகப்பு", Assistant: "ஏஐ உதவியாளர்", Hospitals: "மருத்துவமனைகள்", Medicines: "மருந்துகள்", Schemes: "அரசுத் திட்டங்கள்", ASHA: "ஆஷா உதவி", IVR: "ஐவிஆர் சிமுலேட்டர்", Profile: "சுயவிவரம்" }, heroEyebrow: "பொது சுகாதார வழிகாட்டல், இன்னும் தெளிவாக", heroTitle: "கிராமப்புற சமூகங்களை ஸ்மார்ட் சுகாதாரத்துடன் இணைக்கிறோம்.", heroBody: "கேள்வி கேளுங்கள், அருகிலுள்ள பராமரிப்பைக் கண்டறியுங்கள், மருந்து நினைவூட்டல்களை அமைக்கவும், அதிகாரப்பூர்வத் திட்ட வழிகாட்டலைப் பார்வையிடவும்.", talk: "உதவியாளரிடம் பேசுங்கள்", findCare: "மருத்துவமனைகளைக் கண்டறியவும்", emergency: "அவசரநிலையா? உடனடி உதவி பெறுங்கள்", emergencyBody: "கடுமையான மார்பு வலி, மூச்சுத்திணறல், அதிக இரத்தப்போக்கு, வலிப்பு, மயக்கம் அல்லது உடனடி ஆபத்து இருந்தால் உடனே அவசர சிகிச்சை பெறுங்கள். இந்தியாவில் 112 அல்லது 108-ஐ அழைக்கவும்.", disclaimer: "பொதுவான சுகாதாரத் தகவல் மட்டுமே. இது நோயறிதல் அல்லது சிகிச்சை வழங்குவதில்லை.", speak: "சத்தமாகப் படிக்கவும்", stop: "நிறுத்து", listening: "கேட்கிறது…", medicine: "மருந்து நினைவூட்டல்கள்", schemes: "அரசு சுகாதாரத் திட்டங்கள்", asha: "ஆஷா மற்றும் சமூக உதவி", ivr: "ஊடாடும் அழைப்பு சிமுலேட்டர்", profile: "உங்கள் விருப்பச் சுயவிவரம்", save: "சேமி", addMedicine: "மருந்தைச் சேர்க்கவும்", dosage: "அளவு", time: "நினைவூட்டல் நேரம்", taken: "எடுத்துக்கொண்டேன்", snooze: "பின்னர்", eligibility: "தகுதி வழிகாட்டல்", checkEligibility: "என் வழிகாட்டலைப் பார்க்கவும்", nearby: "அருகிலுள்ள சுகாதாரம்", allowLocation: "என் இருப்பிடத்தைப் பயன்படுத்தவும்", directions: "வழிமுறைகள்", call: "அழைப்பு", noResults: "இதுவரை முடிவுகள் இல்லை.", startIvr: "அழைப்பைத் தொடங்கவும்" }),
  te: localize({ nav: { Home: "హోమ్", Assistant: "ఏఐ సహాయకుడు", Hospitals: "ఆసుపత్రులు", Medicines: "మందులు", Schemes: "ప్రభుత్వ పథకాలు", ASHA: "ఆశా మద్దతు", IVR: "ఐవీఆర్ సిమ్యులేటర్", Profile: "ప్రొఫైల్" }, heroEyebrow: "ప్రజారోగ్య మార్గదర్శకం, మరింత స్పష్టంగా", heroTitle: "గ్రామీణ సమాజాలను స్మార్ట్ ఆరోగ్య సంరక్షణతో కలుపుతున్నాం.", heroBody: "ప్రశ్న అడగండి, సమీప సంరక్షణను కనుగొనండి, మందుల గుర్తింపులను నిర్వహించండి, అధికారిక పథక మార్గదర్శకాన్ని చూడండి.", talk: "సహాయకుడితో మాట్లాడండి", findCare: "ఆసుపత్రులను కనుగొనండి", emergency: "అత్యవసరమా? వెంటనే సహాయం పొందండి", emergencyBody: "తీవ్రమైన ఛాతీ నొప్పి, శ్వాస తీసుకోవడంలో ఇబ్బంది, అధిక రక్తస్రావం, మూర్ఛ, అపస్మారక స్థితి లేదా తక్షణ ప్రమాదం ఉంటే వెంటనే అత్యవసర సంరక్షణ పొందండి. భారతదేశంలో 112 లేదా 108కి కాల్ చేయండి.", disclaimer: "సాధారణ ఆరోగ్య సమాచారం మాత్రమే. ఇది నిర్ధారణ చేయదు లేదా చికిత్స సూచించదు.", speak: "గట్టిగా చదవండి", stop: "ఆపు", listening: "వింటోంది…", medicine: "మందుల గుర్తింపులు", schemes: "ప్రభుత్వ ఆరోగ్య పథకాలు", asha: "ఆశా మరియు సమాజ మద్దతు", ivr: "ఇంటరాక్టివ్ కాల్ సిమ్యులేటర్", profile: "మీ ఐచ్ఛిక ప్రొఫైల్", save: "సేవ్ చేయండి", addMedicine: "మందు జోడించండి", dosage: "మోతాదు", time: "గుర్తింపు సమయం", taken: "తీసుకున్నాను", snooze: "తర్వాత", eligibility: "అర్హత మార్గదర్శకం", checkEligibility: "నా మార్గదర్శకం చూడండి", nearby: "సమీప ఆరోగ్య సంరక్షణ", allowLocation: "నా స్థానాన్ని ఉపయోగించండి", directions: "దిశలు", call: "కాల్", noResults: "ఇంకా ఫలితాలు లేవు.", startIvr: "కాల్ ప్రారంభించండి" }),
};

Object.assign(dictionaries.hi, { history: "सहेजी बातचीत", newChat: "नई बातचीत" });
Object.assign(dictionaries.kn, { history: "ಉಳಿಸಿದ ಸಂಭಾಷಣೆಗಳು", newChat: "ಹೊಸ ಸಂಭಾಷಣೆ" });
Object.assign(dictionaries.ml, { history: "സംരക്ഷിച്ച സംഭാഷണങ്ങൾ", newChat: "പുതിയ സംഭാഷണം" });
Object.assign(dictionaries.ta, { history: "சேமித்த உரையாடல்கள்", newChat: "புதிய உரையாடல்" });
Object.assign(dictionaries.te, { history: "సేవ్ చేసిన సంభాషణలు", newChat: "కొత్త సంభాషణ" });
